name: Selenium 3 Docker Image CI

on:
  push:
    branches: [ "selenium-3", "trunk" ]
  pull_request:
    branches: [ "selenium-3", "trunk" ]

  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        ref: selenium-3
        persist-credentials: false
        fetch-depth: 0
    - run: export DOCKER_BUILDKIT=0
    - run: export COMPOSE_DOCKER_CLI_BUILD=0
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Output Docker info
      run: docker info
    - name: Chrome Version Set
      run: |
        CHROME_DRIVER_VERSION=$(wget --no-verbose -O - "https://chromedriver.storage.googleapis.com/LATEST_RELEASE");
        echo "CHROME_DRIVER_VERSION="$CHROME_DRIVER_VERSION >> $GITHUB_ENV
    - name: Chrome Version
      run: |
        echo "${{ env.CHROME_DRIVER_VERSION }}"
    - name: Build Node Chrome
      run: VERSION=3.141.59-${{ env.CHROME_DRIVER_VERSION }}-${{ steps.date.outputs.date }} make chrome 
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
    - name: Docker image push
      run: docker images
    - name: Docker image tag
      run: docker tag selenium/node-chrome:3.141.59-${{ env.CHROME_DRIVER_VERSION }}-${{ steps.date.outputs.date }} ${{ secrets.DOCKERHUB_USERNAME }}/node-chrome:3.141.59-${{ env.CHROME_DRIVER_VERSION }}-${{ steps.date.outputs.date }}
    - name: Build and push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-chrome:3.141.59-${{ env.CHROME_DRIVER_VERSION }}-${{ steps.date.outputs.date }}
